---

- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure packages are installed.
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ motd_packages }}"
 

- name: Write MOTD config file
  template:
    src: 01-motd.j2
    dest: "/etc/update-motd.d/01-custom"
    owner: "root"
    group: "root"
    mode: 0750
  become: true

- name: Remove file old MOTD
  ansible.builtin.file:
    path: /etc/motd
    state: absent

- name: Add uname details to motd
  ansible.builtin.lineinfile:
    path: /etc/update-motd.d/10-uname
    regexp: '^uname '
    line: uname -snrvm
  when: motd_addunameline  

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/update-motd.d/10-uname
    state: absent
  when: not motd_addunameline  
    
